apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-span-bootstrap-config
  namespace: default
data:
  custom_bootstrap.json: |
    {
      "static_resources": {
        "clusters": [
          {
            "name": "zipkin",
            "connect_timeout": "1s",
            "type": "STRICT_DNS",
            "lb_policy": "ROUND_ROBIN",
            "load_assignment": {
              "cluster_name": "zipkin",
              "endpoints": [
                {
                  "lb_endpoints": [
                    {
                      "endpoint": {
                        "address": {
                          "socket_address": {
                            "address": "zipkin.default.svc.cluster.local",
                            "port_value": 9411
                          }
                        }
                      }
                    }
                  ]
                }
              ]
            }
          }
        ]
      },
      "tracing": {
        "http": {
          "name": "envoy.tracers.zipkin",
          "typed_config": {
            "@type": "type.googleapis.com/envoy.config.trace.v3.ZipkinConfig",
            "collector_cluster": "zipkin",
            "collector_endpoint": "/api/v1/spans/custom",
            "collector_endpoint_version": "HTTP_JSON",
            "trace_id_128bit": true,
            "shared_span_context": true
          }
        }
      }
    }

